
import React, { useState, useEffect, useMemo } from 'react';
import { Hexagram, ViewState, User, Language } from './types';
import { HEXAGRAMS, TRIGRAMS } from './constants';
import { UI_STRINGS } from './i18n';
import HexagramCard from './components/HexagramCard';
import HexagramIcon from './components/HexagramIcon';
import CastingSimulator from './components/CastingSimulator';
import CompassDiagram from './components/CompassDiagram';
import AuthView from './components/AuthView';
import { interpretHexagram, chatWithScholar } from './services/geminiService';
import { getStaticInterpretation } from './data/masterInterpretations';

const App: React.FC = () => {
  const [lang, setLang] = useState<Language>('zh');
  const [view, setView] = useState<ViewState>('grid');
  const [lastView, setLastView] = useState<ViewState>('grid');
  const [selectedHexagram, setSelectedHexagram] = useState<Hexagram | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [aiInterpretation, setAiInterpretation] = useState<string>('');
  const [isLoadingAi, setIsLoadingAi] = useState(false);
  const [chatHistory, setChatHistory] = useState<{user: string, ai: string}[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isAiMode, setIsAiMode] = useState(false);
  const [castTimestamp, setCastTimestamp] = useState<Date | null>(null);
  
  const [user, setUser] = useState<User | null>(null);

  // Sync language with user preference
  useEffect(() => {
    if (user?.preferredLanguage) {
      setLang(user.preferredLanguage);
    }
  }, [user]);

  const t = UI_STRINGS[lang];
  const allHexagrams = useMemo(() => HEXAGRAMS, []);

  const filteredHexagrams = allHexagrams.filter(h => 
    h.name.includes(searchQuery) || 
    h.nameEn.toLowerCase().includes(searchQuery.toLowerCase()) ||
    h.pinyin.toLowerCase().includes(searchQuery.toLowerCase()) ||
    h.number.toString() === searchQuery
  );

  const handleSelectHexagram = (h: Hexagram, isFromCast: boolean = false) => {
    setSelectedHexagram(h);
    setLastView(view === 'detail' ? lastView : view);
    setView('detail');
    setIsAiMode(false); 
    // Now localized using the helper update
    setAiInterpretation(getStaticInterpretation(h.number, lang));
    if (!isFromCast) {
      setCastTimestamp(null);
    }
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleNavigateHexagram = (direction: 'prev' | 'next') => {
    if (!selectedHexagram) return;
    const currentIndex = allHexagrams.findIndex(h => h.number === selectedHexagram.number);
    let nextIndex;
    if (direction === 'prev') {
      nextIndex = (currentIndex - 1 + allHexagrams.length) % allHexagrams.length;
    } else {
      nextIndex = (currentIndex + 1) % allHexagrams.length;
    }
    handleSelectHexagram(allHexagrams[nextIndex]);
  };

  const handleFetchAiWisdom = async () => {
    if (!selectedHexagram) return;
    setIsLoadingAi(true);
    setIsAiMode(true);
    const result = await interpretHexagram(selectedHexagram, lang);
    setAiInterpretation(result || t.aiThinking);
    setIsLoadingAi(false);
  };

  const handleSaveAsFile = () => {
    if (!selectedHexagram || !aiInterpretation) return;
    
    const timeInfo = castTimestamp 
      ? `${t.castMoment}：${castTimestamp.toLocaleString()}` 
      : `${t.back}：${new Date().toLocaleString()}`;

    const userName = user ? user.username : 'Guest Explorer';

    const content = `
========================================
       I CHING REPORT / 解卦报告
========================================

User: ${userName}
Hexagram: ${lang === 'en' ? selectedHexagram.nameEn : selectedHexagram.name} (#${selectedHexagram.number})
Pinyin: ${selectedHexagram.pinyin}
Judgment: ${lang === 'en' ? selectedHexagram.judgmentEn : selectedHexagram.judgment}
Image: ${lang === 'en' ? selectedHexagram.imageEn : selectedHexagram.image}

${timeInfo}

${isAiMode ? t.aiTitle : t.masterTitle}
----------------------------------------
${aiInterpretation}

========================================
Generated by ${t.appName}
${t.footerNote}
========================================
`.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${selectedHexagram.name}_report_${new Date().getTime()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCastComplete = (binary: string) => {
    const found = allHexagrams.find(h => h.binary === binary);
    setCastTimestamp(new Date());
    if (found) {
      handleSelectHexagram(found, true);
    } else {
      handleSelectHexagram(allHexagrams[0], true);
    }
  };

  const handleScholarChat = async () => {
    if (!chatInput.trim()) return;
    const msg = chatInput;
    setChatInput('');
    setChatHistory(prev => [...prev, { user: msg, ai: t.aiThinking }]);
    
    const history = chatHistory.flatMap(h => [
      { role: 'user', parts: [{ text: h.user }] },
      { role: 'model', parts: [{ text: h.ai }] }
    ]);

    const response = await chatWithScholar(msg, history, lang);
    setChatHistory(prev => {
      const newHist = [...prev];
      if (newHist.length > 0) {
        newHist[newHist.length - 1].ai = response || (lang === 'en' ? 'Silence.' : '无法言说。');
      }
      return newHist;
    });
  };

  const handleLogin = (newUser: User) => {
    setUser(newUser);
    if (newUser.preferredLanguage) {
      setLang(newUser.preferredLanguage);
    }
    setView('grid');
  };

  const toggleLanguage = () => {
    const newLang = lang === 'zh' ? 'en' : 'zh';
    setLang(newLang);
    if (user) {
      setUser({ ...user, preferredLanguage: newLang });
    }
    // Update interpretation if one is selected
    if (selectedHexagram) {
      if (!isAiMode) {
        setAiInterpretation(getStaticInterpretation(selectedHexagram.number, newLang));
      }
    }
  };

  const { prevHex, nextHex } = useMemo(() => {
    if (!selectedHexagram) return { prevHex: null, nextHex: null };
    const idx = allHexagrams.findIndex(h => h.number === selectedHexagram.number);
    return {
      prevHex: allHexagrams[(idx - 1 + allHexagrams.length) % allHexagrams.length],
      nextHex: allHexagrams[(idx + 1) % allHexagrams.length],
    };
  }, [selectedHexagram, allHexagrams]);

  const relatedHexagrams = useMemo(() => {
    if (!selectedHexagram) return null;
    const b = selectedHexagram.binary; 
    const oppositeBinary = b.split('').map(char => char === '1' ? '0' : '1').join('');
    const overturnedBinary = b.split('').reverse().join('');
    const nuclearBinary = b.substring(1, 4) + b.substring(2, 5);
    const findHex = (bin: string) => allHexagrams.find(h => h.binary === bin);
    return {
      opposite: findHex(oppositeBinary),
      overturned: findHex(overturnedBinary),
      nuclear: findHex(nuclearBinary)
    };
  }, [selectedHexagram, allHexagrams]);

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="bg-stone-900 text-stone-100 py-6 px-4 shadow-xl sticky top-0 z-50">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-3 cursor-pointer" onClick={() => setView('grid')}>
            <div className="bg-amber-500 p-2 rounded-lg">
              <HexagramIcon binary="111111" size="sm" className="opacity-90" />
            </div>
            <div>
              <h1 className="text-2xl font-bold chinese-font tracking-wide">{t.appName}</h1>
              <p className="text-[10px] text-stone-400 uppercase tracking-widest opacity-80">{t.tagline}</p>
            </div>
          </div>

          <nav className="flex bg-stone-800 rounded-full p-1 border border-stone-700">
            <button onClick={() => setView('grid')} className={`px-4 py-1.5 rounded-full text-sm font-medium transition-all ${view === 'grid' ? 'bg-amber-500 text-stone-900 shadow-lg' : 'text-stone-400 hover:text-white'}`}>{t.navGrid}</button>
            <button onClick={() => setView('compass')} className={`px-4 py-1.5 rounded-full text-sm font-medium transition-all ${view === 'compass' ? 'bg-amber-500 text-stone-900 shadow-lg' : 'text-stone-400 hover:text-white'}`}>{t.navCompass}</button>
            <button onClick={() => setView('cast')} className={`px-4 py-1.5 rounded-full text-sm font-medium transition-all ${view === 'cast' ? 'bg-amber-500 text-stone-900 shadow-lg' : 'text-stone-400 hover:text-white'}`}>{t.navCast}</button>
            <button onClick={() => setView('study')} className={`px-4 py-1.5 rounded-full text-sm font-medium transition-all ${view === 'study' ? 'bg-amber-500 text-stone-900 shadow-lg' : 'text-stone-400 hover:text-white'}`}>{t.navStudy}</button>
          </nav>

          <div className="flex items-center gap-3">
            <button 
              onClick={toggleLanguage}
              className="px-3 py-1.5 rounded-full border border-stone-700 text-stone-400 text-xs hover:border-amber-500 hover:text-white transition-all font-bold uppercase"
            >
              {lang === 'zh' ? 'English' : '中文'}
            </button>
            {user ? (
              <div 
                className="flex items-center gap-3 bg-stone-800 px-4 py-1.5 rounded-full border border-stone-700 hover:border-amber-500 transition-all cursor-pointer group relative"
                onClick={() => setUser(null)}
              >
                <div className="w-8 h-8 rounded-full bg-amber-500 flex items-center justify-center text-stone-900 font-bold shadow-inner">
                  {user.avatar || user.username[0]}
                </div>
                <div className="hidden sm:block">
                  <p className="text-xs font-bold">{user.username}</p>
                  <p className="text-[8px] text-stone-500 group-hover:text-red-400 transition-colors">{t.logout}</p>
                </div>
              </div>
            ) : (
              <button onClick={() => setView('auth')} className="px-6 py-2 bg-amber-500 text-stone-900 rounded-full text-sm font-bold shadow-lg hover:bg-amber-400 transition-all active:scale-95 flex items-center gap-2">
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" /></svg>
                {t.login}
              </button>
            )}
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-grow max-w-6xl w-full mx-auto px-4 py-8">
        {view === 'auth' && (
          <AuthView onLogin={handleLogin} onClose={() => setView('grid')} currentLang={lang} />
        )}

        {view === 'grid' && (
          <div className="space-y-8 animate-in fade-in duration-500">
            <div className="flex flex-col md:flex-row justify-between items-end md:items-center gap-4 border-b border-stone-200 pb-6">
              <div>
                <h2 className="text-3xl font-bold text-stone-800 chinese-font">{t.gridTitle}</h2>
                <p className="text-stone-500 text-sm mt-1">{t.gridSub}</p>
              </div>
              <div className="relative w-full md:w-64">
                <input type="text" placeholder={t.searchPlaceholder} value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="w-full pl-10 pr-4 py-2 bg-white border border-stone-300 rounded-full text-sm focus:ring-2 focus:ring-amber-500 focus:border-amber-500 outline-none transition-all" />
                <svg className="absolute left-3 top-2.5 h-4 w-4 text-stone-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>
              </div>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 md:gap-6">
              {filteredHexagrams.map((h, index) => (
                <HexagramCard key={h.number} hexagram={h} index={index} onClick={handleSelectHexagram} currentLang={lang} />
              ))}
            </div>
          </div>
        )}

        {view === 'compass' && (
          <div className="animate-in fade-in zoom-in-95 duration-700">
            <CompassDiagram onSelectHexagram={handleSelectHexagram} currentLang={lang} />
          </div>
        )}

        {view === 'detail' && selectedHexagram && (
          <div className="animate-in slide-in-from-bottom-4 duration-500">
            <div className="flex flex-col sm:flex-row justify-between items-center mb-8 gap-4">
              <button onClick={() => setView(lastView)} className="flex items-center gap-2 text-stone-500 hover:text-amber-600 transition-colors self-start">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
                {t.back}
              </button>
              
              <div className="flex gap-4 w-full sm:w-auto">
                <button onClick={() => handleNavigateHexagram('prev')} className="flex-1 sm:flex-none flex items-center justify-between sm:justify-start gap-3 px-5 py-2.5 bg-white border border-stone-200 rounded-full text-stone-600 hover:border-amber-400 hover:text-amber-600 transition-all shadow-sm">
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7"/></svg>
                  <span className="text-sm font-medium">{t.prevHex}：{lang === 'en' ? prevHex?.nameEn : prevHex?.name}</span>
                </button>
                <button onClick={() => handleNavigateHexagram('next')} className="flex-1 sm:flex-none flex items-center justify-between sm:justify-start gap-3 px-5 py-2.5 bg-white border border-stone-200 rounded-full text-stone-600 hover:border-amber-400 hover:text-amber-600 transition-all shadow-sm">
                  <span className="text-sm font-medium">{t.nextHex}：{lang === 'en' ? nextHex?.nameEn : nextHex?.name}</span>
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7"/></svg>
                </button>
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
              <div className="lg:col-span-4 flex flex-col items-center">
                <div className="bg-white p-12 rounded-3xl shadow-2xl border border-stone-100 flex flex-col items-center w-full relative">
                  {castTimestamp && (
                    <div className="absolute top-4 left-4 flex items-center gap-1.5 text-[10px] text-amber-700 font-bold bg-amber-50 px-3 py-1 rounded-full border border-amber-200 animate-pulse">
                      <span className="w-1.5 h-1.5 bg-amber-500 rounded-full"></span>
                      {t.castMoment}
                    </div>
                  )}
                  <span className="text-stone-400 text-sm mb-4 tracking-widest uppercase">{lang === 'en' ? `Hexagram ${selectedHexagram.number}` : `第 ${selectedHexagram.number} 卦`}</span>
                  <HexagramIcon binary={selectedHexagram.binary} size="xl" className="mb-8" />
                  <h2 className={`text-5xl font-bold text-stone-800 mb-2 ${lang === 'en' ? 'font-serif' : 'chinese-font'}`}>{lang === 'en' ? selectedHexagram.nameEn : `${selectedHexagram.name}卦`}</h2>
                  <p className="text-lg text-amber-600 font-medium tracking-[0.3em] uppercase">{selectedHexagram.pinyin}</p>
                  
                  <div className="mt-12 grid grid-cols-2 gap-8 w-full border-t border-stone-100 pt-8">
                    <div className="text-center">
                      <p className="text-xs text-stone-400 mb-1">{t.upperTrigram}：{lang === 'en' ? TRIGRAMS[selectedHexagram.upperTrigram].natureEn : TRIGRAMS[selectedHexagram.upperTrigram].nature}</p>
                      <span className={`text-2xl font-bold ${lang === 'en' ? 'font-serif' : 'chinese-font'}`}>{lang === 'en' ? TRIGRAMS[selectedHexagram.upperTrigram].nameEn : selectedHexagram.upperTrigram}</span>
                    </div>
                    <div className="text-center">
                      <p className="text-xs text-stone-400 mb-1">{t.lowerTrigram}：{lang === 'en' ? TRIGRAMS[selectedHexagram.lowerTrigram].natureEn : TRIGRAMS[selectedHexagram.lowerTrigram].nature}</p>
                      <span className={`text-2xl font-bold ${lang === 'en' ? 'font-serif' : 'chinese-font'}`}>{lang === 'en' ? TRIGRAMS[selectedHexagram.lowerTrigram].nameEn : selectedHexagram.lowerTrigram}</span>
                    </div>
                  </div>
                </div>

                {selectedHexagram.solarTerm && (
                  <div className="mt-4 px-6 py-2 bg-amber-600 text-white rounded-full text-sm font-bold shadow-lg">
                    {lang === 'en' ? `Solar Message: ${selectedHexagram.solarTermEn}` : `消息卦：${selectedHexagram.solarTerm}`}
                  </div>
                )}

                <div className="mt-8 p-6 bg-amber-50 rounded-2xl border border-amber-100 w-full italic text-stone-600 text-center leading-relaxed font-serif">
                   “{lang === 'en' ? selectedHexagram.imageEn : selectedHexagram.image}”
                </div>
              </div>

              <div className="lg:col-span-8 space-y-8">
                <section>
                  <h3 className="text-xl font-bold text-stone-800 mb-4 flex items-center gap-2">
                    <div className="w-1 h-6 bg-amber-500 rounded-full"></div>
                    {t.judgmentTitle}
                  </h3>
                  <div className="bg-white p-6 rounded-2xl border border-stone-200 shadow-sm">
                    <p className="text-xl font-medium text-stone-700 mb-4 font-serif">{lang === 'en' ? selectedHexagram.judgmentEn : selectedHexagram.judgment}</p>
                    <p className="text-stone-600 leading-relaxed font-serif">{lang === 'en' ? selectedHexagram.meaningEn : selectedHexagram.meaning}</p>
                  </div>
                </section>

                <section>
                  <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4 gap-4">
                    <h3 className="text-xl font-bold text-stone-800 flex items-center gap-2">
                      <div className="w-1 h-6 bg-amber-500 rounded-full"></div>
                      {isAiMode ? t.aiTitle : t.masterTitle}
                    </h3>
                    <div className="flex items-center gap-2 w-full sm:w-auto">
                      {aiInterpretation && !isLoadingAi && (
                        <button onClick={handleSaveAsFile} className="text-xs px-5 py-2 bg-amber-600 text-white rounded-full hover:bg-amber-500 transition-all flex items-center gap-2 shadow-lg active:scale-95">
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                          {t.downloadReport}
                        </button>
                      )}
                      <button onClick={handleFetchAiWisdom} disabled={isLoadingAi} className="text-xs px-4 py-2 bg-stone-800 text-stone-100 rounded-full hover:bg-stone-700 transition-all flex items-center gap-2 disabled:opacity-50 shadow-md">
                        <svg className={`w-3 h-3 ${isLoadingAi ? 'animate-spin' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                        {isLoadingAi ? t.aiThinking : t.switchAi}
                      </button>
                    </div>
                  </div>
                  
                  <div className={`p-8 rounded-2xl border transition-all duration-500 min-h-[300px] relative ${isAiMode ? 'bg-indigo-50 border-indigo-100' : 'bg-[#fffcf0] border-stone-200 shadow-inner'}`}>
                    <div className="prose prose-stone max-w-none whitespace-pre-wrap text-stone-700 leading-relaxed font-serif">
                      {aiInterpretation}
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
        )}

        {view === 'cast' && (
          <div className="max-w-4xl mx-auto py-12 animate-in zoom-in-95 duration-500">
            <div className="text-center mb-12">
              <h2 className={`text-4xl font-bold text-stone-800 mb-4 ${lang === 'en' ? 'font-serif' : 'chinese-font'}`}>{t.castTitle}</h2>
              <p className="text-stone-500 max-w-lg mx-auto leading-relaxed">{t.castSub}</p>
            </div>
            <CastingSimulator onCastComplete={handleCastComplete} currentLang={lang} />
          </div>
        )}

        {view === 'study' && (
          <div className="max-w-4xl mx-auto flex flex-col h-[70vh] bg-white rounded-3xl shadow-xl border border-stone-200 overflow-hidden animate-in slide-in-from-right-4 duration-500">
            <div className="bg-stone-900 p-6 flex items-center gap-4">
              <div className="w-12 h-12 bg-amber-500 rounded-full flex items-center justify-center text-stone-900 text-2xl font-bold chinese-font">学</div>
              <div>
                <h3 className="text-white font-bold">{t.studyTitle}</h3>
                <p className="text-stone-400 text-xs">{t.studySub}</p>
              </div>
            </div>
            <div className="flex-grow overflow-y-auto p-6 space-y-6 bg-stone-50">
              {chatHistory.length === 0 && (
                <div className="h-full flex flex-col items-center justify-center text-stone-400 text-center px-12">
                  <svg className="w-12 h-12 mb-4 opacity-20" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M18 10c0 3.866-3.582 7-8 7a8.841 8.841 0 01-4.083-.98L2 17l1.338-3.123C2.493 12.767 2 11.434 2 10c0-3.866 3.582-7 8-7s8 3.134 8 7zM7 9H5v2h2V9zm8 0h-2v2h2V9zM9 9h2v2H9V9z" clipRule="evenodd"/></svg>
                  <p className="italic">{lang === 'en' ? '"Though the way is far, study will reach it."' : '“易道虽远，学则可至。”'}</p>
                </div>
              )}
              {chatHistory.map((chat, i) => (
                <div key={i} className="space-y-4">
                  <div className="flex justify-end"><div className="bg-amber-100 text-stone-800 p-4 rounded-2xl rounded-tr-none max-w-[80%] shadow-sm">{chat.user}</div></div>
                  <div className="flex justify-start"><div className="bg-white text-stone-700 p-4 rounded-2xl rounded-tl-none max-w-[80%] shadow-sm border border-stone-100 whitespace-pre-wrap leading-relaxed font-serif">{chat.ai}</div></div>
                </div>
              ))}
            </div>
            <div className="p-6 bg-white border-t border-stone-100 flex gap-4">
              <input type="text" value={chatInput} onChange={(e) => setChatInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && handleScholarChat()} placeholder={t.chatPlaceholder} className="flex-grow px-6 py-3 bg-stone-50 border border-stone-200 rounded-full outline-none focus:ring-2 focus:ring-amber-500 transition-all" />
              <button onClick={handleScholarChat} disabled={!chatInput.trim()} className="bg-stone-800 text-white p-3 rounded-full hover:bg-stone-700 disabled:opacity-50 transition-all shadow-lg">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"/></svg>
              </button>
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="bg-stone-50 py-12 border-t border-stone-200 mt-12">
        <div className="max-w-6xl mx-auto px-4 grid grid-cols-1 md:grid-cols-3 gap-12">
          <div><h4 className={`font-bold text-stone-800 mb-4 text-lg ${lang === 'en' ? 'font-serif' : 'chinese-font'}`}>{t.aboutTitle}</h4><p className="text-stone-500 text-sm leading-relaxed">{t.aboutText}</p></div>
          <div><h4 className={`font-bold text-stone-800 mb-4 text-lg ${lang === 'en' ? 'font-serif' : 'chinese-font'}`}>{t.compassLogicTitle}</h4><p className="text-stone-500 text-sm leading-relaxed">{t.compassLogicText}</p></div>
          <div><h4 className={`font-bold text-stone-800 mb-4 text-lg ${lang === 'en' ? 'font-serif' : 'chinese-font'}`}>{t.solarTermTitle}</h4><p className="text-stone-500 text-sm leading-relaxed">{t.solarTermText}</p></div>
        </div>
        <div className="max-w-6xl mx-auto px-4 mt-12 pt-8 border-t border-stone-200 text-center text-stone-400 text-xs">© 2024 {t.appName} | {t.footerNote}</div>
      </footer>
    </div>
  );
};

export default App;
